/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminErpRouteImport } from './routes/admin.erp'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminMapRouteImport } from './routes/admin.map'
import { Route as AdminMobilePreviewRouteImport } from './routes/admin.mobile-preview'
import { Route as AdminPrintersRouteImport } from './routes/admin.printers'
import { Route as AdminQueuesRouteImport } from './routes/admin.queues'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStatsRouteImport } from './routes/admin.stats'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminTerminalsRouteImport } from './routes/admin.terminals'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWarehousesRouteImport } from './routes/admin.warehouses'
import { Route as MobileIndexRouteImport } from './routes/mobile.index'
import { Route as MobileDashboardRouteImport } from './routes/mobile.dashboard'
import { Route as MobileInventoryRouteImport } from './routes/mobile.inventory'
import { Route as MobileLocationsRouteImport } from './routes/mobile.locations'
import { Route as MobileLoginRouteImport } from './routes/mobile.login'
import { Route as MobileMyTasksRouteImport } from './routes/mobile.my-tasks'
import { Route as MobilePickingRouteImport } from './routes/mobile.picking'
import { Route as MobileReceivingRouteImport } from './routes/mobile.receiving'
import { Route as MobileScanRouteImport } from './routes/mobile.scan'
import { Route as MobileSyncRouteImport } from './routes/mobile.sync'
import { Route as MobileProductCodeRouteImport } from './routes/mobile.product.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminErpRoute = AdminErpRouteImport.update({
  id: '/erp',
  path: '/erp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMobilePreviewRoute = AdminMobilePreviewRouteImport.update({
  id: '/mobile-preview',
  path: '/mobile-preview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrintersRoute = AdminPrintersRouteImport.update({
  id: '/printers',
  path: '/printers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQueuesRoute = AdminQueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTerminalsRoute = AdminTerminalsRouteImport.update({
  id: '/terminals',
  path: '/terminals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWarehousesRoute = AdminWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AdminRoute,
} as any)
const MobileIndexRoute = MobileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MobileRoute,
} as any)
const MobileDashboardRoute = MobileDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MobileRoute,
} as any)
const MobileInventoryRoute = MobileInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => MobileRoute,
} as any)
const MobileLocationsRoute = MobileLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => MobileRoute,
} as any)
const MobileLoginRoute = MobileLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MobileRoute,
} as any)
const MobileMyTasksRoute = MobileMyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => MobileRoute,
} as any)
const MobilePickingRoute = MobilePickingRouteImport.update({
  id: '/picking',
  path: '/picking',
  getParentRoute: () => MobileRoute,
} as any)
const MobileReceivingRoute = MobileReceivingRouteImport.update({
  id: '/receiving',
  path: '/receiving',
  getParentRoute: () => MobileRoute,
} as any)
const MobileScanRoute = MobileScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => MobileRoute,
} as any)
const MobileSyncRoute = MobileSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => MobileRoute,
} as any)
const MobileProductCodeRoute = MobileProductCodeRouteImport.update({
  id: '/product/$code',
  path: '/product/$code',
  getParentRoute: () => MobileRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/mobile': typeof MobileRouteWithChildren
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/erp': typeof AdminErpRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/mobile-preview': typeof AdminMobilePreviewRoute
  '/admin/printers': typeof AdminPrintersRoute
  '/admin/queues': typeof AdminQueuesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/terminals': typeof AdminTerminalsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/warehouses': typeof AdminWarehousesRoute
  '/mobile/dashboard': typeof MobileDashboardRoute
  '/mobile/inventory': typeof MobileInventoryRoute
  '/mobile/locations': typeof MobileLocationsRoute
  '/mobile/login': typeof MobileLoginRoute
  '/mobile/my-tasks': typeof MobileMyTasksRoute
  '/mobile/picking': typeof MobilePickingRoute
  '/mobile/receiving': typeof MobileReceivingRoute
  '/mobile/scan': typeof MobileScanRoute
  '/mobile/sync': typeof MobileSyncRoute
  '/admin/': typeof AdminIndexRoute
  '/mobile/': typeof MobileIndexRoute
  '/mobile/product/$code': typeof MobileProductCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/erp': typeof AdminErpRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/mobile-preview': typeof AdminMobilePreviewRoute
  '/admin/printers': typeof AdminPrintersRoute
  '/admin/queues': typeof AdminQueuesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/terminals': typeof AdminTerminalsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/warehouses': typeof AdminWarehousesRoute
  '/mobile/dashboard': typeof MobileDashboardRoute
  '/mobile/inventory': typeof MobileInventoryRoute
  '/mobile/locations': typeof MobileLocationsRoute
  '/mobile/login': typeof MobileLoginRoute
  '/mobile/my-tasks': typeof MobileMyTasksRoute
  '/mobile/picking': typeof MobilePickingRoute
  '/mobile/receiving': typeof MobileReceivingRoute
  '/mobile/scan': typeof MobileScanRoute
  '/mobile/sync': typeof MobileSyncRoute
  '/admin': typeof AdminIndexRoute
  '/mobile': typeof MobileIndexRoute
  '/mobile/product/$code': typeof MobileProductCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/mobile': typeof MobileRouteWithChildren
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/erp': typeof AdminErpRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/mobile-preview': typeof AdminMobilePreviewRoute
  '/admin/printers': typeof AdminPrintersRoute
  '/admin/queues': typeof AdminQueuesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/terminals': typeof AdminTerminalsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/warehouses': typeof AdminWarehousesRoute
  '/mobile/dashboard': typeof MobileDashboardRoute
  '/mobile/inventory': typeof MobileInventoryRoute
  '/mobile/locations': typeof MobileLocationsRoute
  '/mobile/login': typeof MobileLoginRoute
  '/mobile/my-tasks': typeof MobileMyTasksRoute
  '/mobile/picking': typeof MobilePickingRoute
  '/mobile/receiving': typeof MobileReceivingRoute
  '/mobile/scan': typeof MobileScanRoute
  '/mobile/sync': typeof MobileSyncRoute
  '/admin/': typeof AdminIndexRoute
  '/mobile/': typeof MobileIndexRoute
  '/mobile/product/$code': typeof MobileProductCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/mobile'
    | '/admin/alerts'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/erp'
    | '/admin/logs'
    | '/admin/map'
    | '/admin/mobile-preview'
    | '/admin/printers'
    | '/admin/queues'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/tasks'
    | '/admin/terminals'
    | '/admin/users'
    | '/admin/warehouses'
    | '/mobile/dashboard'
    | '/mobile/inventory'
    | '/mobile/locations'
    | '/mobile/login'
    | '/mobile/my-tasks'
    | '/mobile/picking'
    | '/mobile/receiving'
    | '/mobile/scan'
    | '/mobile/sync'
    | '/admin/'
    | '/mobile/'
    | '/mobile/product/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/alerts'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/erp'
    | '/admin/logs'
    | '/admin/map'
    | '/admin/mobile-preview'
    | '/admin/printers'
    | '/admin/queues'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/tasks'
    | '/admin/terminals'
    | '/admin/users'
    | '/admin/warehouses'
    | '/mobile/dashboard'
    | '/mobile/inventory'
    | '/mobile/locations'
    | '/mobile/login'
    | '/mobile/my-tasks'
    | '/mobile/picking'
    | '/mobile/receiving'
    | '/mobile/scan'
    | '/mobile/sync'
    | '/admin'
    | '/mobile'
    | '/mobile/product/$code'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/mobile'
    | '/admin/alerts'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/erp'
    | '/admin/logs'
    | '/admin/map'
    | '/admin/mobile-preview'
    | '/admin/printers'
    | '/admin/queues'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/tasks'
    | '/admin/terminals'
    | '/admin/users'
    | '/admin/warehouses'
    | '/mobile/dashboard'
    | '/mobile/inventory'
    | '/mobile/locations'
    | '/mobile/login'
    | '/mobile/my-tasks'
    | '/mobile/picking'
    | '/mobile/receiving'
    | '/mobile/scan'
    | '/mobile/sync'
    | '/admin/'
    | '/mobile/'
    | '/mobile/product/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  MobileRoute: typeof MobileRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/erp': {
      id: '/admin/erp'
      path: '/erp'
      fullPath: '/admin/erp'
      preLoaderRoute: typeof AdminErpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mobile-preview': {
      id: '/admin/mobile-preview'
      path: '/mobile-preview'
      fullPath: '/admin/mobile-preview'
      preLoaderRoute: typeof AdminMobilePreviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/printers': {
      id: '/admin/printers'
      path: '/printers'
      fullPath: '/admin/printers'
      preLoaderRoute: typeof AdminPrintersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/queues': {
      id: '/admin/queues'
      path: '/queues'
      fullPath: '/admin/queues'
      preLoaderRoute: typeof AdminQueuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/terminals': {
      id: '/admin/terminals'
      path: '/terminals'
      fullPath: '/admin/terminals'
      preLoaderRoute: typeof AdminTerminalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/warehouses': {
      id: '/admin/warehouses'
      path: '/warehouses'
      fullPath: '/admin/warehouses'
      preLoaderRoute: typeof AdminWarehousesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/mobile/': {
      id: '/mobile/'
      path: '/'
      fullPath: '/mobile/'
      preLoaderRoute: typeof MobileIndexRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/dashboard': {
      id: '/mobile/dashboard'
      path: '/dashboard'
      fullPath: '/mobile/dashboard'
      preLoaderRoute: typeof MobileDashboardRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/inventory': {
      id: '/mobile/inventory'
      path: '/inventory'
      fullPath: '/mobile/inventory'
      preLoaderRoute: typeof MobileInventoryRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/locations': {
      id: '/mobile/locations'
      path: '/locations'
      fullPath: '/mobile/locations'
      preLoaderRoute: typeof MobileLocationsRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/login': {
      id: '/mobile/login'
      path: '/login'
      fullPath: '/mobile/login'
      preLoaderRoute: typeof MobileLoginRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/my-tasks': {
      id: '/mobile/my-tasks'
      path: '/my-tasks'
      fullPath: '/mobile/my-tasks'
      preLoaderRoute: typeof MobileMyTasksRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/picking': {
      id: '/mobile/picking'
      path: '/picking'
      fullPath: '/mobile/picking'
      preLoaderRoute: typeof MobilePickingRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/receiving': {
      id: '/mobile/receiving'
      path: '/receiving'
      fullPath: '/mobile/receiving'
      preLoaderRoute: typeof MobileReceivingRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/scan': {
      id: '/mobile/scan'
      path: '/scan'
      fullPath: '/mobile/scan'
      preLoaderRoute: typeof MobileScanRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/sync': {
      id: '/mobile/sync'
      path: '/sync'
      fullPath: '/mobile/sync'
      preLoaderRoute: typeof MobileSyncRouteImport
      parentRoute: typeof MobileRoute
    }
    '/mobile/product/$code': {
      id: '/mobile/product/$code'
      path: '/product/$code'
      fullPath: '/mobile/product/$code'
      preLoaderRoute: typeof MobileProductCodeRouteImport
      parentRoute: typeof MobileRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminErpRoute: typeof AdminErpRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminMobilePreviewRoute: typeof AdminMobilePreviewRoute
  AdminPrintersRoute: typeof AdminPrintersRoute
  AdminQueuesRoute: typeof AdminQueuesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStatsRoute: typeof AdminStatsRoute
  AdminTasksRoute: typeof AdminTasksRoute
  AdminTerminalsRoute: typeof AdminTerminalsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWarehousesRoute: typeof AdminWarehousesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertsRoute: AdminAlertsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminErpRoute: AdminErpRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMapRoute: AdminMapRoute,
  AdminMobilePreviewRoute: AdminMobilePreviewRoute,
  AdminPrintersRoute: AdminPrintersRoute,
  AdminQueuesRoute: AdminQueuesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStatsRoute: AdminStatsRoute,
  AdminTasksRoute: AdminTasksRoute,
  AdminTerminalsRoute: AdminTerminalsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWarehousesRoute: AdminWarehousesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MobileRouteChildren {
  MobileDashboardRoute: typeof MobileDashboardRoute
  MobileInventoryRoute: typeof MobileInventoryRoute
  MobileLocationsRoute: typeof MobileLocationsRoute
  MobileLoginRoute: typeof MobileLoginRoute
  MobileMyTasksRoute: typeof MobileMyTasksRoute
  MobilePickingRoute: typeof MobilePickingRoute
  MobileReceivingRoute: typeof MobileReceivingRoute
  MobileScanRoute: typeof MobileScanRoute
  MobileSyncRoute: typeof MobileSyncRoute
  MobileIndexRoute: typeof MobileIndexRoute
  MobileProductCodeRoute: typeof MobileProductCodeRoute
}

const MobileRouteChildren: MobileRouteChildren = {
  MobileDashboardRoute: MobileDashboardRoute,
  MobileInventoryRoute: MobileInventoryRoute,
  MobileLocationsRoute: MobileLocationsRoute,
  MobileLoginRoute: MobileLoginRoute,
  MobileMyTasksRoute: MobileMyTasksRoute,
  MobilePickingRoute: MobilePickingRoute,
  MobileReceivingRoute: MobileReceivingRoute,
  MobileScanRoute: MobileScanRoute,
  MobileSyncRoute: MobileSyncRoute,
  MobileIndexRoute: MobileIndexRoute,
  MobileProductCodeRoute: MobileProductCodeRoute,
}

const MobileRouteWithChildren =
  MobileRoute._addFileChildren(MobileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  MobileRoute: MobileRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
